name: Cypress Tests

# trigger para workflow ser executado
# push -> Todo push em qualquer branch
on: [ push ]

jobs:
  cypress-run-api:
    # if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/api_testing/*.cy.js